/**
 * Stable, client-safe API error codes.
 * Messages must never include secrets, stack traces, or private content.
 */
export const errorCodes = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  PERMISSION_DENIED: "PERMISSION_DENIED",
  WORKSPACE_UNAVAILABLE: "WORKSPACE_UNAVAILABLE",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  STALE_CONFLICT: "STALE_CONFLICT",
  RATE_LIMITED: "RATE_LIMITED",
  DEPENDENCY_UNAVAILABLE: "DEPENDENCY_UNAVAILABLE",
  CONFIGURATION_ERROR: "CONFIGURATION_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  ACCOUNT_DEACTIVATED: "ACCOUNT_DEACTIVATED",
  ACCOUNT_RESTRICTED: "ACCOUNT_RESTRICTED",
  ACCOUNT_PROFILE_MISSING: "ACCOUNT_PROFILE_MISSING",
  REQUEST_TOO_LARGE: "REQUEST_TOO_LARGE",
} as const;

export type ErrorCode = (typeof errorCodes)[keyof typeof errorCodes];
